version: '3'

services:

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl/
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    links:
      - mariadb:db

  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret