version: '3'

networks:
  net1:
    driver: bridge

services:

  api:
    image: nginx:1.13
    container_name: api
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl/
    depends_on:
      - php
    networks:
      - net1

  php:
    image: php:8.1-fpm
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    links:
      - mariadb:db
    networks:
        - net1

  mariadb:
    image: mariadb:10.3
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MARIADB_DATABASE: MVC
    networks:
      - net1

  redis:
    image: redis
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
    networks:
      - net1

  socket:
    image: node
    user: "node"
    volumes:
      - ./socket:/home/node/app
    ports:
      - 5000:5000
    working_dir: /home/node/app
    command: "npm start"
    networks:
      - net1

  client:
    image: nginx
    container_name: client
    volumes:
      - ./client:/var/www/html/
      - ./docker/client/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - api
      - redis
    networks:
      - net1